### ISSUE TITLE
Inherit old codebase of e-conomic

### ISSUE THREAD

**Issue by cobraz** [borglind/e-conomic-client#1]
Hello 👋

Back in 2016, Visma decided to close e-conomic in Norway. Let me start with a clear check – this client is for this software, correct? 👇

![Visma e-conomic](https://community.visma.com/t5/image/serverpage/image-id/195i3C4447C09CE2BD56/image-size/large?v=1.0&px=999 "Visma E-conomic")

If so, I'm happy to say that I have a lot of codebase that works with E-conomic. Sure, it's quite old. Last commit is probably back in 2016, but if want – I can share it with you, and you can release it under Open Source licence. Of course, it might need some work, but it might be easier than starting from scratch!

Cheers! 🍺

**Comment by borglind** [comment]
@cobraz  Yes, this is the software :)  Just to clarify, I never intended this to be a fully featured client with access to all the endpoints etc, but more of a helper for consuming and consolidating their REST and SOAP APIs - especially the SOAP api, since it’s not that straight forward and it unlocks some pretty important endpoints if you use their inventory module.
Does your code support their SOAP api? If yes, I’d love to have a look. I only plan of doing a couple of updates to this repo, mainly making the REST and SOAP functions output the same results / errors.

**Comment by cobraz** [comment]
Just found out that this codebase is buried on one of my older hard drives, unfortunately. I’m going to move most of that data to a newer medium soon, so if and when I find it I’ll let you know :)
